# Generated by Django 5.0.2 on 2024-09-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(blank=True, choices=[('gym', 'Gym'), ('pool', 'Swimming Pool'), ('wifi', 'WiFi'), ('laundry', 'Laundry'), ('parking', 'Parking'), ('other', 'Other')], max_length=20, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_image', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('available_seat', models.IntegerField()),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('customized', 'Customized')], max_length=20)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('inquiry', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room_Management.room')),
            ],
        ),
    ]
