# Generated by Django 5.0.2 on 2024-09-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
    ]
